---
title: "p8105_hw6_jt3174"
author: "Jingyi Tang"
date: "11/23/2019"
output: github_document
---

```{r set up}

# ensure reproductivity
set.seed(1)

# load library
library(tidyverse)
library(modelr)
library(mgcv)
library(viridis)
library(ggridges)

knitr::opts_chunk$set(
  # display the code in the code truck above its results in the final document
  echo = TRUE,
  # do not display any warning messages generated by the code
  warning = FALSE,
  # set the figure to be 8 x 6, and the proportion it takes to be 90%
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)

# setting a global options for continuous data color family and a different format to set discrete data to have a color family
options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# have a minimal theme and legends at the bottom
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```


## Problem 1

```{r load and clean data}

# Load and clean the data for regression analysis (i.e. convert numeric to factor where appropriate, check for missing data, etc.).

baby = read_csv("./data/birthweight.csv") %>% 
  # clean names
  janitor::clean_names() %>% 
  # use case_when to give the values of certain variables new values
  mutate(
    # baby’s sex (male = 1, female = 2)
    babysex = as.factor(case_when(
      babysex == 1 ~ "male",
      babysex == 2 ~ "female"
    )),
    # father’s race (1 = White, 2 = Black, 3 = Asian, 4 = Puerto Rican, 8 = Other, 9 = Unknown)
    frace = as.factor(case_when(
      frace == 1 ~ "White",
      frace == 2 ~ "Black",
      frace == 3 ~ "Asian",
      frace == 4 ~ "Puerto Rican",
      frace == 8 ~ "Other",
      frace == 9 ~ "Unknown"
    )),
    # presence of malformations that could affect weight (0 = absent, 1 = present)
    malform = as.factor(case_when(
      malform == 0 ~ "absent",
      malform == 1 ~ "present"
    )),
    # mother’s race (1 = White, 2 = Black, 3 = Asian, 4 = Puerto Rican, 8 = Other)
    mrace = as.factor(case_when(
      mrace == 1 ~ "White",
      mrace == 2 ~ "Black",
      mrace == 3 ~ "Asian",
      mrace == 4 ~ "Puerto Rican",
      mrace == 8 ~ "Other"
    ))
  )

baby

```

